name: citatio

on:
  push:
    branches: ['main']
    paths: ['asmtransformers/**', 'citatio/**']
  pull_request:
    paths: ['asmtransformers/**', 'citatio/**']

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: citatio/
    steps:
      - uses: actions/checkout@v6
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.13'
          cache: true
          cache-dependency-path: 'citatio/pdm.lock'
      - run: pdm install --group check --no-default
      - run: pdm run check
  test:
    runs-on: ubuntu-latest
    needs: check
    defaults:
      run:
        working-directory: citatio/
    services:
      pgvector:
        image: pgvector/pgvector:pg18
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: tee4ieCh1jeerahkie3u
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v6
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.13'
          cache: true
          cache-dependency-path: 'citatio/pdm.lock'
      - run: pdm install --group test
      - run: pdm run test
      - run: pdm run integration-test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: tee4ieCh1jeerahkie3u
